version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
  node-app-container:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
